import { Lead, LeadStatus, Message, MessageDirection } from "./types"

const now = new Date()

const pastDate = (days: number, hours = 0) =>
  new Date(now.getTime() - (days * 24 * 60 * 60 * 1000) - (hours * 60 * 60 * 1000))

const futureDate = (hours: number) =>
  new Date(now.getTime() + (hours * 60 * 60 * 1000))

export const MOCK_LEADS: Lead[] = [
  // Descubiertos
  {
    id: "l1",
    hostAirbnbId: "h1",
    threadId: null,
    name: "Carlos Rivera",
    hostProfileUrl: "https://airbnb.com/users/show/1",
    primaryListingUrl: "https://airbnb.com/rooms/1",
    primaryListingName: "Apartamento Centro Histórico",
    totalProperties: 12,
    companyName: "Rivera Stays",
    isSuperhost: true,
    market: "Bogotá",
    icpSkipReason: null,
    status: LeadStatus.LEAD_DISCOVERED,
    businessScale: null,
    painPoints: null,
    executiveSummary: null,
    lastContactedAt: null,
    nextFollowUpAt: null,
    botReplyCount: 0,
    calLinkSent: false,
    calBookedAt: null,
    createdAt: pastDate(0, 2),
    updatedAt: pastDate(0, 2),
  },
  {
    id: "l2",
    hostAirbnbId: "h2",
    threadId: null,
    name: "Ana Martínez",
    hostProfileUrl: "https://airbnb.com/users/show/2",
    primaryListingUrl: "https://airbnb.com/rooms/2",
    primaryListingName: "Casa de Playa - Vista al Mar",
    totalProperties: 4,
    companyName: null,
    isSuperhost: false,
    market: "Cartagena",
    icpSkipReason: "below_min",
    status: LeadStatus.LEAD_DISCOVERED,
    businessScale: "Operador mediano con propiedades en la costa.",
    painPoints: "Menciona problemas de limpieza en reviews recientes.",
    executiveSummary: "Buen prospecto por sus dolores de limpieza. Contactar por el lado operativo.",
    lastContactedAt: null,
    nextFollowUpAt: null,
    botReplyCount: 0,
    calLinkSent: false,
    calBookedAt: null,
    createdAt: pastDate(1),
    updatedAt: pastDate(1),
  },
  
  // INITIAL_MSG_SENT
  {
    id: "l3",
    hostAirbnbId: "h3",
    threadId: "t3",
    name: "Roberto Gómez",
    hostProfileUrl: "https://airbnb.com/users/show/3",
    primaryListingUrl: "https://airbnb.com/rooms/3",
    primaryListingName: "Loft en Poblado",
    totalProperties: 25,
    companyName: "Gómez Management",
    isSuperhost: true,
    market: "Medellín",
    icpSkipReason: null,
    status: LeadStatus.INITIAL_MSG_SENT,
    businessScale: "Gran volumen, agencia estructurada.",
    painPoints: "Coordinación de personal y soporte 24/7.",
    executiveSummary: "Gran cuenta. Enfocar en automatización total con Agent Pilot.",
    lastContactedAt: pastDate(0, 5),
    nextFollowUpAt: futureDate(19),
    botReplyCount: 0,
    calLinkSent: false,
    calBookedAt: null,
    createdAt: pastDate(2),
    updatedAt: pastDate(0, 5),
  },

  // FOLLOW_UP_1_SENT (Urgent - vencido)
  {
    id: "l4",
    hostAirbnbId: "h4",
    threadId: "t4",
    name: "Laura Castillo",
    hostProfileUrl: "https://airbnb.com/users/show/4",
    primaryListingUrl: "https://airbnb.com/rooms/4",
    primaryListingName: "Villa Montaña",
    totalProperties: 8,
    companyName: null,
    isSuperhost: true,
    market: "Bogotá",
    icpSkipReason: null,
    status: LeadStatus.FOLLOW_UP_1_SENT,
    businessScale: "Operador mediano rural.",
    painPoints: null,
    executiveSummary: null,
    lastContactedAt: pastDate(2),
    nextFollowUpAt: pastDate(0, 1), // Vencido
    botReplyCount: 0,
    calLinkSent: false,
    calBookedAt: null,
    createdAt: pastDate(5),
    updatedAt: pastDate(2),
  },

  // REPLIED_IN_PROGRESS
  {
    id: "l5",
    hostAirbnbId: "h5",
    threadId: "t5",
    name: "Andrés Silva",
    hostProfileUrl: "https://airbnb.com/users/show/5",
    primaryListingUrl: "https://airbnb.com/rooms/5",
    primaryListingName: "Estudio Minimalista - Zona G",
    totalProperties: 3,
    companyName: null,
    isSuperhost: false,
    market: "Bogotá",
    icpSkipReason: "below_min",
    status: LeadStatus.REPLIED_IN_PROGRESS,
    businessScale: "Pequeño inversor.",
    painPoints: "Dudas técnicas sobre integración con Guesty.",
    executiveSummary: "Preguntó por integración directa con su PMS.",
    lastContactedAt: pastDate(0, 1),
    nextFollowUpAt: null,
    botReplyCount: 1,
    calLinkSent: true,
    calBookedAt: null,
    createdAt: pastDate(6),
    updatedAt: pastDate(0, 1),
  },

  // HUMAN_TAKEOVER
  {
    id: "l6",
    hostAirbnbId: "h6",
    threadId: "t6",
    name: "Daniela Vargas",
    hostProfileUrl: "https://airbnb.com/users/show/6",
    primaryListingUrl: "https://airbnb.com/rooms/6",
    primaryListingName: "Penthouse de Lujo",
    totalProperties: 40,
    companyName: "Vargas Luxury Rentals",
    isSuperhost: true,
    market: "Medellín",
    icpSkipReason: "above_max",
    status: LeadStatus.HUMAN_TAKEOVER,
    businessScale: "Agencia muy grande.",
    painPoints: "Múltiples plataformas, mucho overhead manual.",
    executiveSummary: "El bot no pudo responder sobre costos específicos de onboarding.",
    lastContactedAt: pastDate(0, 0.5),
    nextFollowUpAt: null,
    botReplyCount: 3,
    calLinkSent: false,
    calBookedAt: null,
    createdAt: pastDate(10),
    updatedAt: pastDate(0, 0.5),
  },

  // CLOSED_WON
  {
    id: "l7",
    hostAirbnbId: "h7",
    threadId: "t7",
    name: "Esteban Moreno",
    hostProfileUrl: "https://airbnb.com/users/show/7",
    primaryListingUrl: "https://airbnb.com/rooms/7",
    primaryListingName: "Cabaña Bosque",
    totalProperties: 18,
    companyName: "EcoStays",
    isSuperhost: true,
    market: "Bogotá",
    icpSkipReason: null,
    status: LeadStatus.CLOSED_WON,
    businessScale: "Mediano-grande, enfoque ecológico.",
    painPoints: "Gestión remota de mantenimientos.",
    executiveSummary: "Agendó llamada para mañana tras el link.",
    lastContactedAt: pastDate(1),
    nextFollowUpAt: null,
    botReplyCount: 2,
    calLinkSent: true,
    calBookedAt: pastDate(2),
    createdAt: pastDate(15),
    updatedAt: pastDate(1),
  },
]

export const MOCK_MESSAGES: Message[] = [
  // Mensajes para l5 (REPLIED_IN_PROGRESS)
  {
    id: "m1",
    leadId: "l5",
    prospectAccountId: null,
    direction: MessageDirection.OUTBOUND,
    content: "Hola Andrés, vi tu anuncio Estudio Minimalista. Noté en tu perfil que administras 3 propiedades. Hemos ayudado a operadores de tu tamaño a poner la atención a huéspedes y limpiezas en piloto automático usando IA. ¿Tienes algún cuello de botella operativo actualmente?",
    aiIntent: null,
    sentAt: pastDate(1),
  },
  {
    id: "m2",
    leadId: "l5",
    prospectAccountId: null,
    direction: MessageDirection.INBOUND,
    content: "Suena interesante, pero ¿cómo se integra esto con mi cuenta de Guesty?",
    aiIntent: "DUDA_TECNICA",
    sentAt: pastDate(0, 2),
  },
  {
    id: "m3",
    leadId: "l5",
    prospectAccountId: null,
    direction: MessageDirection.OUTBOUND,
    content: "Nos integramos holísticamente a tus canales y PMS (incluyendo Guesty) para que todo se gestione directamente desde el chat. Como tienes 3 propiedades, lo mejor es hacer un diagnóstico rápido para ver tu setup actual. Elige el horario que mejor te quede en este link y te lo muestro en 10 minutos: cal.com/agent-pilot",
    aiIntent: null,
    sentAt: pastDate(0, 1),
  },

  // Mensajes para l6 (HUMAN_TAKEOVER)
  {
    id: "m4",
    leadId: "l6",
    prospectAccountId: null,
    direction: MessageDirection.INBOUND,
    content: "Me interesa, pero quiero saber exactamente cuánto me cuesta el setup inicial para mis 40 propiedades antes de agendar ninguna llamada.",
    aiIntent: "DUDA_TECNICA",
    sentAt: pastDate(0, 0.6),
  },
  {
    id: "m5",
    leadId: "l6",
    prospectAccountId: null,
    direction: MessageDirection.SYSTEM,
    content: "IA Pausada: Límite de complejidad o botReplyCount superado. Se requiere intervención humana.",
    aiIntent: null,
    sentAt: pastDate(0, 0.5),
  }
]
